/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ReturnsRouteImport } from './routes/returns'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as PackagingAndShippingRouteImport } from './routes/packaging-and-shipping'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CartRouteImport } from './routes/cart'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShippingToCityRouteImport } from './routes/shipping-to.$city'
import { Route as ProductsCategorySlugRouteImport } from './routes/products_.$categorySlug'
import { Route as ProductSlugRouteImport } from './routes/product.$slug'
import { Route as OccasionSlugRouteImport } from './routes/occasion.$slug'
import { Route as CategorySlugRouteImport } from './routes/category.$slug'
import { Route as BlogSlugRouteImport } from './routes/blog_.$slug'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ReturnsRoute = ReturnsRouteImport.update({
  id: '/returns',
  path: '/returns',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const PackagingAndShippingRoute = PackagingAndShippingRouteImport.update({
  id: '/packaging-and-shipping',
  path: '/packaging-and-shipping',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShippingToCityRoute = ShippingToCityRouteImport.update({
  id: '/shipping-to/$city',
  path: '/shipping-to/$city',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsCategorySlugRoute = ProductsCategorySlugRouteImport.update({
  id: '/products_/$categorySlug',
  path: '/products/$categorySlug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductSlugRoute = ProductSlugRouteImport.update({
  id: '/product/$slug',
  path: '/product/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const OccasionSlugRoute = OccasionSlugRouteImport.update({
  id: '/occasion/$slug',
  path: '/occasion/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CategorySlugRoute = CategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog_/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/packaging-and-shipping': typeof PackagingAndShippingRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/products': typeof ProductsRouteWithChildren
  '/returns': typeof ReturnsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/category/$slug': typeof CategorySlugRoute
  '/occasion/$slug': typeof OccasionSlugRoute
  '/product/$slug': typeof ProductSlugRoute
  '/products/$categorySlug': typeof ProductsCategorySlugRoute
  '/shipping-to/$city': typeof ShippingToCityRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/packaging-and-shipping': typeof PackagingAndShippingRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/products': typeof ProductsRouteWithChildren
  '/returns': typeof ReturnsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/category/$slug': typeof CategorySlugRoute
  '/occasion/$slug': typeof OccasionSlugRoute
  '/product/$slug': typeof ProductSlugRoute
  '/products/$categorySlug': typeof ProductsCategorySlugRoute
  '/shipping-to/$city': typeof ShippingToCityRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/packaging-and-shipping': typeof PackagingAndShippingRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/products': typeof ProductsRouteWithChildren
  '/returns': typeof ReturnsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/blog_/$slug': typeof BlogSlugRoute
  '/category/$slug': typeof CategorySlugRoute
  '/occasion/$slug': typeof OccasionSlugRoute
  '/product/$slug': typeof ProductSlugRoute
  '/products_/$categorySlug': typeof ProductsCategorySlugRoute
  '/shipping-to/$city': typeof ShippingToCityRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/blog'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/faq'
    | '/packaging-and-shipping'
    | '/privacy-policy'
    | '/products'
    | '/returns'
    | '/sitemap.xml'
    | '/terms'
    | '/blog/$slug'
    | '/category/$slug'
    | '/occasion/$slug'
    | '/product/$slug'
    | '/products/$categorySlug'
    | '/shipping-to/$city'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/blog'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/faq'
    | '/packaging-and-shipping'
    | '/privacy-policy'
    | '/products'
    | '/returns'
    | '/sitemap.xml'
    | '/terms'
    | '/blog/$slug'
    | '/category/$slug'
    | '/occasion/$slug'
    | '/product/$slug'
    | '/products/$categorySlug'
    | '/shipping-to/$city'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/blog'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/faq'
    | '/packaging-and-shipping'
    | '/privacy-policy'
    | '/products'
    | '/returns'
    | '/sitemap.xml'
    | '/terms'
    | '/blog_/$slug'
    | '/category/$slug'
    | '/occasion/$slug'
    | '/product/$slug'
    | '/products_/$categorySlug'
    | '/shipping-to/$city'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BlogRoute: typeof BlogRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  PackagingAndShippingRoute: typeof PackagingAndShippingRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  ProductsRoute: typeof ProductsRouteWithChildren
  ReturnsRoute: typeof ReturnsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  BlogSlugRoute: typeof BlogSlugRoute
  CategorySlugRoute: typeof CategorySlugRoute
  OccasionSlugRoute: typeof OccasionSlugRoute
  ProductSlugRoute: typeof ProductSlugRoute
  ProductsCategorySlugRoute: typeof ProductsCategorySlugRoute
  ShippingToCityRoute: typeof ShippingToCityRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/returns': {
      id: '/returns'
      path: '/returns'
      fullPath: '/returns'
      preLoaderRoute: typeof ReturnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packaging-and-shipping': {
      id: '/packaging-and-shipping'
      path: '/packaging-and-shipping'
      fullPath: '/packaging-and-shipping'
      preLoaderRoute: typeof PackagingAndShippingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shipping-to/$city': {
      id: '/shipping-to/$city'
      path: '/shipping-to/$city'
      fullPath: '/shipping-to/$city'
      preLoaderRoute: typeof ShippingToCityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products_/$categorySlug': {
      id: '/products_/$categorySlug'
      path: '/products/$categorySlug'
      fullPath: '/products/$categorySlug'
      preLoaderRoute: typeof ProductsCategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$slug': {
      id: '/product/$slug'
      path: '/product/$slug'
      fullPath: '/product/$slug'
      preLoaderRoute: typeof ProductSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/occasion/$slug': {
      id: '/occasion/$slug'
      path: '/occasion/$slug'
      fullPath: '/occasion/$slug'
      preLoaderRoute: typeof OccasionSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$slug': {
      id: '/category/$slug'
      path: '/category/$slug'
      fullPath: '/category/$slug'
      preLoaderRoute: typeof CategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog_/$slug': {
      id: '/blog_/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BlogRoute: BlogRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  PackagingAndShippingRoute: PackagingAndShippingRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  ProductsRoute: ProductsRouteWithChildren,
  ReturnsRoute: ReturnsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  BlogSlugRoute: BlogSlugRoute,
  CategorySlugRoute: CategorySlugRoute,
  OccasionSlugRoute: OccasionSlugRoute,
  ProductSlugRoute: ProductSlugRoute,
  ProductsCategorySlugRoute: ProductsCategorySlugRoute,
  ShippingToCityRoute: ShippingToCityRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
